### ISSUE TITLE
THREE.Scene: autoUpdate was renamed to matrixWorldAutoUpdate in r144.

### ISSUE THREAD

**Issue by kyndle-ozzo** [iyinchao/three-css3d#3]
This warning prints continually when calling CSS3DRenderer.render().

My threejs version is 0.150.1 and my three-css3d version is 1.0.5.

**Comment by kyndle-ozzo** [comment]
I have submitted a PR to address this.

**Comment by iyinchao** [comment]
Sorry for slow response, I'm on vacation these days. Thank you!

**Comment by iyinchao** [comment]
fixed at #4 and released version 1.0.6
